In [3]:
import numpy as np

In [4]:
# Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами
vector = np.arange(1, 11)
print("Одновимірний масив (вектор) з першими 10-ма натуральними числами:")
print(vector)

Одновимірний масив (вектор) з першими 10-ма натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями
matrix = np.zeros((3, 3))
print("Двовимірний масив (матриця) розміром 3x3, заповнений нулями:")
print(matrix)

Двовимірний масив (матриця) розміром 3x3, заповнений нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10
random_matrix_int = np.random.randint(1, 11, size=(5, 5))
print("Масив розміром 5x5 з випадковими цілими числами від 1 до 10:")
print(random_matrix_int)

Масив розміром 5x5 з випадковими цілими числами від 1 до 10:
[[ 5  6  4  8  4]
 [ 4 10  5  3  6]
 [ 7  4  2 10 10]
 [ 8  3  3  4  6]
 [ 4  8  2  1  6]]


In [7]:
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1
random_matrix_float = np.random.rand(4, 4)
print("Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:")
print(random_matrix_float)

Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:
[[0.46394605 0.36217433 0.50726869 0.4936115 ]
 [0.16764545 0.08896716 0.33859373 0.15657456]
 [0.17429345 0.67513416 0.02255569 0.85712754]
 [0.08909972 0.49099448 0.85973256 0.94566131]]


In [8]:
# Створіть два одновимірні масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Виконайте поелементні операції додавання, віднімання та множення
add_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2
print("Додавання двох масивів:")
print(add_result)
print("Віднімання двох масивів:")
print(subtract_result)
print("Множення двох масивів:")
print(multiply_result)

Додавання двох масивів:
[13 19 11  5  8]
Віднімання двох масивів:
[-5 -1  1  1 -6]
Множення двох масивів:
[36 90 30  6  7]


In [9]:
# Створіть два вектори розміром 7, заповніть довільними числами
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

# Знайдіть їх скалярний добуток
dot_product = np.dot(vector1, vector2)
print("Скалярний добуток двох векторів:")
print(dot_product)

Скалярний добуток двох векторів:
1.822187014060624


In [10]:
# Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Перемножте їх між собою
matrix_product = np.dot(matrix1, matrix2)
print("Результат множення двох матриць:")
print(matrix_product)

Результат множення двох матриць:
[[10 40 28]
 [13 45 35]]


In [11]:
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10
matrix3x3 = np.random.randint(1, 11, size=(3, 3))

# Знайдіть її обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix3x3)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої матриці.")

Обернена матриця:
[[ 0.03883495 -0.33009709  0.26213592]
 [-0.32038835  0.22330097  0.08737864]
 [ 0.16504854  0.09708738 -0.13592233]]


In [12]:
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1
matrix4x4 = np.random.rand(4, 4)

# Транспонуйте її
transposed_matrix = np.transpose(matrix4x4)
print("Транспонована матриця:")
print(transposed_matrix)

Транспонована матриця:
[[0.02677132 0.10235171 0.57136797 0.15595028]
 [0.03284426 0.43044693 0.22972368 0.21434395]
 [0.41240719 0.12277337 0.91301319 0.24220154]
 [0.5545769  0.70100528 0.005119   0.25147717]]


In [13]:
# Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами
matrix3x4 = np.random.randint(1, 11, size=(3, 4))
vector4 = np.random.randint(1, 11, size=4)

# Перемножте матрицю на вектор
matrix_vector_product = np.dot(matrix3x4, vector4)
print("Результат множення матриці на вектор:")
print(matrix_vector_product)

Результат множення матриці на вектор:
[127 181 240]


In [14]:
# Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами
matrix2x3 = np.random.rand(2, 3)
vector3 = np.random.rand(3)

# Перемножте матрицю на вектор
matrix_vector_product2 = np.dot(matrix2x3, vector3)
print("Результат множення матриці на вектор:")
print(matrix_vector_product2)

Результат множення матриці на вектор:
[0.92628924 0.45642688]


In [15]:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами
matrixA = np.random.randint(1, 11, size=(2, 2))
matrixB = np.random.randint(1, 11, size=(2, 2))

# Виконайте їхнє поелементне множення
elementwise_product = matrixA * matrixB
print("Поелементне множення двох матриць:")
print(elementwise_product)

Поелементне множення двох матриць:
[[12 15]
 [ 4  4]]


In [16]:
# Виконайте множення матриць
matrix_product2 = np.dot(matrixA, matrixB)
print("Результат множення двох матриць:")
print(matrix_product2)

Результат множення двох матриць:
[[32 16]
 [14  7]]


In [17]:
# Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100
matrix5x5 = np.random.randint(1, 101, size=(5, 5))

# Знайдіть суму елементів матриці
matrix_sum = np.sum(matrix5x5)
print("Сума елементів матриці:")
print(matrix_sum)

Сума елементів матриці:
1378


In [18]:
# Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами
matrixC = np.random.randint(1, 11, size=(4, 4))
matrixD = np.random.randint(1, 11, size=(4, 4))

# Знайдіть їхню різницю
matrix_difference = matrixC - matrixD
print("Різниця двох матриць:")
print(matrix_difference)

Різниця двох матриць:
[[-5  3  4  7]
 [ 5 -4 -7 -8]
 [ 6  3 -4  0]
 [ 2  0 -5  0]]


In [19]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами
matrixE = np.random.rand(3, 3)

# Знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці
row_sums = np.sum(matrixE, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(column_vector)

Вектор-стовпчик з сумами елементів кожного рядка:
[[2.19314593]
 [2.25082184]
 [1.43763314]]


In [20]:
# Створіть матрицю розміром 3x4 з довільними цілими числами
matrixF = np.random.randint(1, 11, size=(3, 4))

# Створіть матрицю з квадратами цих чисел
squared_matrix = matrixF ** 2
print("Матриця з квадратами чисел:")
print(squared_matrix)

Матриця з квадратами чисел:
[[ 25   1   9 100]
 [ 36  36   9  81]
 [ 81   1  81  49]]


In [21]:
# Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50
vectorG = np.random.randint(1, 51, size=4)

# Знайдіть вектор з квадратними коренями цих чисел
square_root_vector = np.sqrt(vectorG)
print("Вектор з квадратними коренями чисел:")
print(square_root_vector)

Вектор з квадратними коренями чисел:
[3.87298335 4.58257569 5.65685425 6.63324958]
