In [2]:
import numpy as np

# Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами
vector = np.arange(1, 11)
print("Одновимірний масив (вектор) з першими 10-ма натуральними числами:")
print(vector)

# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями
matrix = np.zeros((3, 3))
print("Двовимірний масив (матриця) розміром 3x3, заповнений нулями:")
print(matrix)

# Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10
random_matrix_int = np.random.randint(1, 11, size=(5, 5))
print("Масив розміром 5x5 з випадковими цілими числами від 1 до 10:")
print(random_matrix_int)

# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1
random_matrix_float = np.random.rand(4, 4)
print("Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:")
print(random_matrix_float)

# Створіть два одновимірні масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Виконайте поелементні операції додавання, віднімання та множення
add_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2
print("Додавання двох масивів:")
print(add_result)
print("Віднімання двох масивів:")
print(subtract_result)
print("Множення двох масивів:")
print(multiply_result)

# Створіть два вектори розміром 7, заповніть довільними числами
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

# Знайдіть їх скалярний добуток
dot_product = np.dot(vector1, vector2)
print("Скалярний добуток двох векторів:")
print(dot_product)

# Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Перемножте їх між собою
matrix_product = np.dot(matrix1, matrix2)
print("Результат множення двох матриць:")
print(matrix_product)

# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10
matrix3x3 = np.random.randint(1, 11, size=(3, 3))

# Знайдіть її обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix3x3)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої матриці.")

# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1
matrix4x4 = np.random.rand(4, 4)

# Транспонуйте її
transposed_matrix = np.transpose(matrix4x4)
print("Транспонована матриця:")
print(transposed_matrix)

# Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами
matrix3x4 = np.random.randint(1, 11, size=(3, 4))
vector4 = np.random.randint(1, 11, size=4)

# Перемножте матрицю на вектор
matrix_vector_product = np.dot(matrix3x4, vector4)
print("Результат множення матриці на вектор:")
print(matrix_vector_product)

# Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами
matrix2x3 = np.random.rand(2, 3)
vector3 = np.random.rand(3)

# Перемножте матрицю на вектор
matrix_vector_product2 = np.dot(matrix2x3, vector3)
print("Результат множення матриці на вектор:")
print(matrix_vector_product2)

# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами
matrixA = np.random.randint(1, 11, size=(2, 2))
matrixB = np.random.randint(1, 11, size=(2, 2))

# Виконайте їхнє поелементне множення
elementwise_product = matrixA * matrixB
print("Поелементне множення двох матриць:")
print(elementwise_product)

# Виконайте множення матриць
matrix_product2 = np.dot(matrixA, matrixB)
print("Результат множення двох матриць:")
print(matrix_product2)

# Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100
matrix5x5 = np.random.randint(1, 101, size=(5, 5))

# Знайдіть суму елементів матриці
matrix_sum = np.sum(matrix5x5)
print("Сума елементів матриці:")
print(matrix_sum)

# Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами
matrixC = np.random.randint(1, 11, size=(4, 4))
matrixD = np.random.randint(1, 11, size=(4, 4))

# Знайдіть їхню різницю
matrix_difference = matrixC - matrixD
print("Різниця двох матриць:")
print(matrix_difference)

# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами
matrixE = np.random.rand(3, 3)

# Знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці
row_sums = np.sum(matrixE, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(column_vector)

# Створіть матрицю розміром 3x4 з довільними цілими числами
matrixF = np.random.randint(1, 11, size=(3, 4))

# Створіть матрицю з квадратами цих чисел
squared_matrix = matrixF ** 2
print("Матриця з квадратами чисел:")
print(squared_matrix)

# Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50
vectorG = np.random.randint(1, 51, size=4)

# Знайдіть вектор з квадратними коренями цих чисел
square_root_vector = np.sqrt(vectorG)
print("Вектор з квадратними коренями чисел:")
print(square_root_vector)


Одновимірний масив (вектор) з першими 10-ма натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]
Двовимірний масив (матриця) розміром 3x3, заповнений нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Масив розміром 5x5 з випадковими цілими числами від 1 до 10:
[[ 4  1  8  9  6]
 [ 7 10  3  2 10]
 [10  8  8  4  1]
 [ 4  4  1  6  9]
 [ 4  4  8  4  5]]
Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:
[[0.49833406 0.04093256 0.56274576 0.52958677]
 [0.14072158 0.01294772 0.63274346 0.91787978]
 [0.7349144  0.81887917 0.7253923  0.4577908 ]
 [0.78550105 0.83469797 0.7747546  0.15477237]]
Додавання двох масивів:
[19 15 12  4 16]
Віднімання двох масивів:
[-1 -3  8 -2 -2]
Множення двох масивів:
[90 54 20  3 63]
Скалярний добуток двох векторів:
3.3991490187146898
Результат множення двох матриць:
[[54 40 23]
 [50 68 41]]
Обернена матриця:
[[-0.05627706  0.27272727 -0.06493506]
 [ 0.17748918 -0.09090909 -0.02597403]
 [-0.14285714  0.          0.14285714]]
Транспонована матриця:
[[0.15874